# Site settings
title: "Ayush's Blog"
description: "Trust me, I am intelligent"
#url: "/" # the base hostname & protocol for your site
url: "https://techmyway.com"
# Used by jekyll-seo-tag for images and JSON-LD
logo: "/favicon.png"
twitter:
  username: named_none
  card: summary_large_image
author:
  name: Ayush Goel
  email: ayushgoel111@gmail.com
  twitter: named_none
  github: ayushgoel
  linkedIn:
    country: in
    username: ayushgoel
  stackoverflowID: 1685709

# include pages folder for generation
include: ['_pages']

liquid:
  error_mode: warn

# Build settings
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Pagination
paginate: 10
paginate_path: /page:num/

#Defaults
defaults:
 -
  scope:
    path: "" # an empty string here means all files in the project
    type: "posts"
  values:
    layout: "post"
 -
  scope:
    path: "" # an empty string here means all files in the project
    type: "pages"
  values:
    layout: "page"

plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-include-cache

# https://github.com/jekyll/jekyll-seo-tag
lang: en
