# Site settings
title: Ayush Goel's Blog
email: ayushgoel111@gmail.com
description: Tech posts from Ayush
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: named_none

# Build settings
markdown: kramdown

#pagination
paginate: 5

#Defaults
defaults
 -
  scope:
    path: "" # an empty string here means all files in the project
    type: "posts"
  values:
    layout: "post"
-
  scope:
    path: "" # an empty string here means all files in the project
    type: "pages"
  values:
    layout: "page"
    author: "Ayush Goel"
