# Site settings
title: Ayush's Blog
description: ""#Tech posts from Ayush
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://ayushgoel.github.io" # the base hostname & protocol for your site
author:
  name: Ayush Goel
  email: ayushgoel111@gmail.com
  twitter: named_none
  github: ayushgoel
  linkedIn:
    country: in
    username: ayushgoel
  stackoverflowID: 1685709

# include pages folder for generation
include: ['_pages']

# Build settings
markdown: kramdown

# Pagination
paginate: 5
paginate_path: /page:num/

#Defaults
defaults:
 -
  scope:
    path: "" # an empty string here means all files in the project
    type: "posts"
  values:
    layout: "post"
 -
  scope:
    path: "" # an empty string here means all files in the project
    type: "pages"
  values:
    layout: "page"
    author: "Ayush Goel"
